name: clean_arch
server:
  name: clean_arch
  host: localhost
  port: 3000
log:
  code: zap
  level: debug
  file_name: tmp/clean_arch_test.log
database:
  code: sqldb
  driver_name: postgres
  url_address: "host=localhost port=5432 user=postgres password=postgres dbname=clean_arch_test sslmode=disable"
contact:
  name: Robin Shi
  email: robinshi@outlook.com
